version: '3'

services:
  db:
    container_name: postgres
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: example_db
    volumes:
      - my-db:/var/lib/postgresql/data
volumes:
  my-db:

